# Generated by Django 5.2.8 on 2025-11-23 21:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('user', models.OneToOneField(help_text='Django User associated with this approver', on_delete=django.db.models.deletion.CASCADE, related_name='approver_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Approver',
                'verbose_name_plural': 'Approvers',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DomainEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('VEHICLE', 'vehicle'), ('EMPLOYEE', 'employee'), ('OTHER', 'other')], help_text='Entity type', max_length=10, verbose_name='Entity type')),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(max_length=255, verbose_name='Entity Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
            options={
                'verbose_name': 'Domain Entity',
                'verbose_name_plural': 'Domain Entities',
                'indexes': [models.Index(fields=['entity_type', 'object_id'], name='documents_d_entity__8abb9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('document_type', models.CharField(choices=[('FOTO_VEHICULO', 'Vehicle Photo'), ('DOC_EMPLEADO', 'Employee Document'), ('CERT_TRIBUTARIO', 'Tax Certificate'), ('OTRO', 'Other')], default='OTRO', max_length=50, verbose_name='Document Type')),
                ('size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Size (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME Type')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='File Hash (SHA-256)')),
                ('bucket_key', models.CharField(help_text='Full path or file ID in the storage bucket', max_length=500, verbose_name='Bucket Path')),
                ('validation_status', models.CharField(blank=True, choices=[(None, 'No Validation'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], help_text='Overall status calculated from validations', max_length=1, null=True, verbose_name='Validation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Download Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.company', verbose_name='Company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('domain_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.domainentity', verbose_name='Domain Entity')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField(help_text='Order number of the step in the validation flow', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Step Order')),
                ('step_name', models.CharField(help_text='Descriptive name of the validation step', max_length=255, verbose_name='Step Name')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='Status')),
                ('reason', models.TextField(blank=True, help_text='Reason or comment about the approval or rejection', null=True, verbose_name='Reason/Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the validation record was created', verbose_name='Creation Date')),
                ('action_date', models.DateTimeField(blank=True, help_text='Date when the validation was approved or rejected', null=True, verbose_name='Action Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('actor_approver', models.ForeignKey(blank=True, help_text='Approver who approved or rejected the validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_performed', to='documents.approver', verbose_name='Actor Approver')),
                ('assigned_approver', models.ForeignKey(blank=True, help_text='Approver who must approve or reject this validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_assigned', to='documents.approver', verbose_name='Assigned Approver')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document Validation',
                'verbose_name_plural': 'Document Validations',
                'ordering': ['document', 'step_order'],
                'indexes': [models.Index(fields=['document', 'status'], name='documents_d_documen_2272ab_idx'), models.Index(fields=['document', 'step_order'], name='documents_d_documen_f3fef0_idx'), models.Index(fields=['actor_approver', 'action_date'], name='documents_d_actor_a_30c80a_idx'), models.Index(fields=['assigned_approver', 'status'], name='documents_d_assigne_dd5012_idx')],
                'unique_together': {('document', 'step_order')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'validation_status'], name='documents_d_company_0e4b11_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['domain_entity'], name='documents_d_domain__7abbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
    ]
