# Generated by Django 5.2.8 on 2025-11-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bucket_key',
            field=models.CharField(help_text='Full path or file ID in the storage bucket (must be unique)', max_length=500, unique=True, verbose_name='Bucket Path'),
        ),
    ]
