# Generated by Django 5.2.8 on 2025-11-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_bucket_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_documen_40c475_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
    ]
